version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.18.0
    steps:
      - checkout
      - run:
          name: npm install
          command: |
            sudo npm install

      - run:
          name: Build Project
          command: |
            npm run build-storybook
      - run:
          name: Deploying to Azure Blob
          command: |
            sudo wget https://aka.ms/downloadazcopy-v10-linux
            tar -xvf *azcopy*
            cp azcopy_linux_amd64*/azcopy .
            ./azcopy copy "storybook-static" "$bloburl" --recursive

      - run:
          name: Pushing to Nexus Repo
          command: |
            npm run build
            cd dist/pattern-lib
            npm config set strict-ssl false
            npm set //monitor.connected2fiber.com/nexus/repository/c2f-npm-releases/$npmtoken
            npm publish

workflows:
  build-storybook:
    jobs:
      - build:
          filters:
            branches:
              only:
                - development
